### PR TITLE
Bump base 64 dependency

### PR DESCRIPTION
**Pull request by TornaxO7**
Ok, now the destination branch should be correct!

### CODE REVIEW

**Comment by TornaxO7** [comment]
I don't understand... why does git tell me that there's no change here? If I do `git diff master` in my `bump_base_64_dependency` branch, then I'm getting the following output:

<details>

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index e9e4b73..eb86f3a 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -7,6 +7,10 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ## [Unreleased]
 
+## [0.2.2] - 2023-03-26
+
+* Bumping up version of the `base64` crate to `0.21.0`.
+
 ## [0.2.1] - 2023-01-08
 
 ### Fixed
@@ -73,7 +77,8 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 First official release.
 
-[unreleased]: https://github.com/soywod/rfc2047-decoder/compare/v0.2.1...HEAD
+[unreleased]: https://github.com/soywod/rfc2047-decoder/compare/v0.2.2...HEAD
+[0.2.2]: https://github.com/soywod/rfc2047-decoder/compare/v0.2.1...v0.2.2
 [0.2.1]: https://github.com/soywod/rfc2047-decoder/compare/v0.2.0...v0.2.1
 [0.2.0]: https://github.com/soywod/rfc2047-decoder/compare/v0.1.3...v0.2.0
 [0.1.3]: https://github.com/soywod/rfc2047-decoder/compare/v0.1.2...v0.1.3
diff --git a/Cargo.toml b/Cargo.toml
index 8bd0cdb..8e17d7f 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -1,7 +1,7 @@
 [package]
 name = "rfc2047-decoder"
 description = "Rust library for decoding RFC 2047 MIME Message Headers."
-version = "0.2.1" # do not forget html_root_url
+version = "0.2.2" # do not forget html_root_url
 authors = ["soywod <clement.douin@posteo.net>", "TornaxO7 <tornax07@gmail.com>"]
 edition = "2018"
 repository = "https://github.com/soywod/rfc2047-decoder"
@@ -16,7 +16,7 @@ readme = "README.md"
 name = "rfc2047_decoder"
 
 [dependencies]
-base64 = "0.13.0"
+base64 = "0.21.0"
 charset = "0.1.2"
 chumsky = "0.9.2"
 memchr = "2.5.0"
diff --git a/src/evaluator.rs b/src/evaluator.rs
index f55919a..87d8e1d 100644
--- a/src/evaluator.rs
+++ b/src/evaluator.rs
@@ -1,4 +1,7 @@
-use base64::{CharacterSet, Config};
+use base64::{
+    alphabet,
+    engine::{GeneralPurpose, GeneralPurposeConfig}, Engine,
+};
 use charset::Charset;
 use std::{result, string};
 use thiserror::Error;
@@ -18,8 +21,13 @@ pub enum Error {
 type Result<T> = result::Result<T, Error>;
 
 fn decode_base64(encoded_bytes: Vec<u8>) -> Result<Vec<u8>> {
-    let config = Config::new(CharacterSet::Standard, true).decode_allow_trailing_bits(true);
-    let decoded_bytes = base64::decode_config(&encoded_bytes, config)?;
+    let base64_decoder = {
+        let config = GeneralPurposeConfig::new().with_decode_allow_trailing_bits(true);
+        GeneralPurpose::new(&alphabet::STANDARD, config)
+    };
+
+    let decoded_bytes = base64_decoder.decode(encoded_bytes)?;
+
     Ok(decoded_bytes)
 }
```

</details>

So this should be fine, no? @soywod may I ask, if you have any suggestions, how to fix this issue here?

**Comment by soywod** [comment]
Your feature is already on `develop` so there is nothing more to merge I guess?

**Comment by TornaxO7** [comment]
image

hm... the problem is, that github doesn't "recognize" it, if I'm seeing it correctly :thinking:

**Comment by soywod** [comment]
I see what's wrong, let me fix then I will explain you!

**Comment by soywod** [comment]
The thing is you merged stuff on `master`. The only thing we should merge on `master` is merge commit from `develop` for new releases, nothing else. When the release PR is merged we can attach a tag (on `master`) and this should trigger the publish on `crates.io` (I do it this time, try again for the next one :wink:)

**Comment by TornaxO7** [comment]
> The only thing we should merge on master is merge commit from develop for new releases, nothing else

Yes, I accidently chose the wrong destination branch ;-;

> (I do it this time, try again for the next one wink)

Thanks! :+1:

**Pull request closed without merging**
