### PR TITLE
7 lexer using chumsky

### PR DESCRIPTION
**Pull request by TornaxO7**
This PR let's [`chumsky`](https://crates.io/crates/chumsky) handle the parsing stuff.

Resolves:
- https://github.com/soywod/rfc2047-decoder/issues/7
- https://github.com/soywod/rfc2047-decoder/issues/3 as you can see [here](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L130) and [here](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L328) its test
-  https://github.com/soywod/rfc2047-decoder/issues/1 which is done [here](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L146) and which is checked [here](https://github.com/TornaxO7/rfc2047-decoder/blob/7_lexer_using_chumsky/src/lexer.rs#L314)

### CODE REVIEW

**Comment by TornaxO7** [comment]
hm... I'm a little bit unsure about my tests since some tests are executed "twice" or multiple times but take your time first to review it, then we can talk about it.

**Comment by TornaxO7** [comment]
@soywod (just a little reminder, because I don't know if you got notified)

**Comment by soywod** [comment]
I saw, I'm just off for a while I will check when I come back. Thank you for the feature!

**Comment by TornaxO7** [comment]
@soywod did you take a look or should I take care of this?

**Comment by soywod** [comment]
Hard to review because there is to many changes, but looks good to me! Thank you :tada:

**Pull request merged**
